module.exports = {
    // LOGIN TYPES
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    REMOVE_USER_SESSION: "REMOVE_USER_SESSION",

    // ALERT TYPES
    ON_SHOW_TOAST: "ON_SHOW_TOAST",
    ON_HIDE_TOAST: "ON_HIDE_TOAST",

    // REGISTER
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",

    // REGISTER
    RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",


    SET_REDIRECT_ROUTE: "SET_REDIRECT_ROUTE",
    REMOVE_REDIRECT_ROUTE: "SET_REDIRECT_ROUTE",

    SET_SESSION: "SET_SESSION",
    REMOVE_SESSION: "REMOVE_SESSION",

    SET_AUTH_SESSION: "SET_AUTH_SESSION",

    REMOVE_AUTH_SESSION: "REMOVE_AUTH_SESSION",

};